baseURL: http://localhost/
title: Hugo SCSS Building
# alternate copyright company text
copyright: Sean Emerson
# controls number of pages displayed on list pages
paginate: 5
# controls the summary length on list pages
summaryLength: 7
# this is required so that Hugo will render markdown to HTML
markup:
  goldmark:
    renderer:
      unsafe: true
enableGitInfo: true

params:
  dateFormat: "02/01/2006"
  widgets: 
  - recent-posts
